language: node_js
node_js:
  - "12"

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker login --username=zhangzongcheng@qilun --password=a1234567 registry.cn-hangzhou.aliyuncs.com
  - docker tag dockertest registry.cn-hangzhou.aliyuncs.com/project-temp/test_docker:1.0.0
  - docker push registry.cn-hangzhou.aliyuncs.com/project-temp/test_docker:1.0.0
