language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker login --username=zhangzongcheng@qilun registry.cn-hangzhou.aliyuncs.com
  - docker build -t mike-zongcheng/test:latest .
  - docker push mike-zongcheng/test:latest
